//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationFinderServiceAppl
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tasks", Namespace="http://schemas.datacontract.org/2004/07/LocationFinderServiceAppl")]
    public partial class Tasks : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CreatedByField;
        
        private System.DateTime CreationDateField;
        
        private string DescriptionField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string TaskIdField;
        
        private string TaskNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskId
        {
            get
            {
                return this.TaskIdField;
            }
            set
            {
                this.TaskIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName
        {
            get
            {
                return this.TaskNameField;
            }
            set
            {
                this.TaskNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILocationFinder")]
public interface ILocationFinder
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/getAllTasks", ReplyAction="http://tempuri.org/ILocationFinder/getAllTasksResponse")]
    LocationFinderServiceAppl.Tasks[] getAllTasks();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/getAllTasks", ReplyAction="http://tempuri.org/ILocationFinder/getAllTasksResponse")]
    System.Threading.Tasks.Task<LocationFinderServiceAppl.Tasks[]> getAllTasksAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/getTaskByID", ReplyAction="http://tempuri.org/ILocationFinder/getTaskByIDResponse")]
    LocationFinderServiceAppl.Tasks[] getTaskByID();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/getTaskByID", ReplyAction="http://tempuri.org/ILocationFinder/getTaskByIDResponse")]
    System.Threading.Tasks.Task<LocationFinderServiceAppl.Tasks[]> getTaskByIDAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/AddTask", ReplyAction="http://tempuri.org/ILocationFinder/AddTaskResponse")]
    void AddTask(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationFinder/AddTask", ReplyAction="http://tempuri.org/ILocationFinder/AddTaskResponse")]
    System.Threading.Tasks.Task AddTaskAsync(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILocationFinderChannel : ILocationFinder, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LocationFinderClient : System.ServiceModel.ClientBase<ILocationFinder>, ILocationFinder
{
    
    public LocationFinderClient()
    {
    }
    
    public LocationFinderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LocationFinderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LocationFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public LocationFinderServiceAppl.Tasks[] getAllTasks()
    {
        return base.Channel.getAllTasks();
    }
    
    public System.Threading.Tasks.Task<LocationFinderServiceAppl.Tasks[]> getAllTasksAsync()
    {
        return base.Channel.getAllTasksAsync();
    }
    
    public LocationFinderServiceAppl.Tasks[] getTaskByID()
    {
        return base.Channel.getTaskByID();
    }
    
    public System.Threading.Tasks.Task<LocationFinderServiceAppl.Tasks[]> getTaskByIDAsync()
    {
        return base.Channel.getTaskByIDAsync();
    }
    
    public void AddTask(string id)
    {
        base.Channel.AddTask(id);
    }
    
    public System.Threading.Tasks.Task AddTaskAsync(string id)
    {
        return base.Channel.AddTaskAsync(id);
    }
}
